name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - name: Cache conda
      uses: actions/cache@v2
      env:
        CACHE_NUMBER: 0  # Increase this value to reset cache if .github/mrchem-gha.yml has not changed
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ matrix.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('.github/classyq-gha.yml') }}

    - uses: conda-incubator/setup-miniconda@v2
      with:
          mamba-version: "*"
          channels: conda-forge,defaults
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: classyq-gha
          environment-file: .github/classyq-gha.yml
          channel-priority: true
          python-version: 3.9
          use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -GNinja

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
